# Generated by Django 5.0.6 on 2024-06-04 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_categoria_plato_activo_plato_plato_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='id_categoria',
            field=models.ForeignKey(blank=True, db_column='idCategoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(db_column='idCategoria', primary_key=True, serialize=False),
        ),
    ]
