# Generated by Django 5.0.6 on 2024-06-05 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_plato_id_categoria_alter_categoria_id_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='id_categoria',
            field=models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='catalogos.categoria'),
        ),
    ]
