# Generated by Django 5.0.6 on 2024-06-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_plato_id_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='plato_activo',
            new_name='cat_activo',
        ),
    ]
