# Generated by Django 5.0.6 on 2024-06-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_plato_id_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='foto_categoria',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/categorias/'),
        ),
        migrations.AddField(
            model_name='plato',
            name='foto_plato',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/platos/'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='des_categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='desc_plato',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
