# Generated by Django 5.0.6 on 2024-06-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='email_proveedor',
            field=models.EmailField(default='prov@email.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fono_proveedor',
            field=models.DecimalField(decimal_places=2, default=1111, max_digits=10, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='password_proveedor',
            field=models.CharField(default='test1234', max_length=100),
            preserve_default=False,
        ),
    ]
