# Generated by Django 5.0.6 on 2024-07-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='domicilio_proveedor',
            field=models.CharField(default='s/n', max_length=100),
        ),
    ]
