# Generated by Django 5.0.6 on 2024-07-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_proveedor_domicilio_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='fono_proveedor',
            field=models.IntegerField(max_length=15),
        ),
    ]
