# Generated by Django 5.0.6 on 2024-07-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_alter_proveedor_fono_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='fono_proveedor',
            field=models.IntegerField(),
        ),
    ]
