# Generated by Django 5.0.6 on 2024-06-11 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=100)),
                ('des_categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_categoria', models.ImageField(blank=True, null=True, upload_to='img/categorias/')),
                ('cat_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nom_plato', models.CharField(max_length=100)),
                ('desc_plato', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_plato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oferta_plato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('foto_plato', models.ImageField(blank=True, null=True, upload_to='fotos/platos/')),
                ('desc_activo', models.BooleanField(default=True)),
                ('plato_activo', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(db_column='idCategoria', default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.categoria')),
            ],
        ),
    ]
