# Generated by Django 5.0.6 on 2024-06-22 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cant_venta',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_venta',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='monto_venta',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cant_item',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pdido',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pedido',
            name='monto_pedido',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
