# Generated by Django 5.0.6 on 2024-07-12 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_item', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_agregado', models.DateField(auto_now_add=True)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.pedido')),
                ('plato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.plato')),
            ],
        ),
    ]
