# Generated by Django 5.0.6 on 2024-06-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_categoria_foto_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plato',
            old_name='desc_activo',
            new_name='descuento_activo',
        ),
    ]
