# Generated by Django 5.0.6 on 2024-07-12 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
