# Generated by Django 5.0.6 on 2024-07-12 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('ecommerce', '0003_entrega_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrega',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', default='1', on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrega',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', default='1', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pedido'),
            preserve_default=False,
        ),
    ]
