# Generated by Django 5.0.6 on 2024-06-15 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_rename_desc_plato_plato_descripcion_plato_and_more'),
        ('usuarios', '0003_remove_proveedor_id_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='id_proveedor',
            field=models.ForeignKey(db_column='idProveedor', default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.proveedor'),
        ),
    ]
