# Generated by Django 5.0.6 on 2024-07-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_entrega_entregado_entrega_id_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
