# Generated by Django 5.0.6 on 2024-06-15 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_plato_id_proveedor'),
        ('usuarios', '0007_remove_venta_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, db_column='idProveedor', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.proveedor'),
        ),
    ]
