# Generated by Django 5.0.6 on 2024-07-12 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_pedido_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='plato',
            field=models.ForeignKey(blank=True, db_column='id_plato', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.plato'),
        ),
    ]
