# Generated by Django 5.0.6 on 2024-06-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_plato_id_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='id_proveedor',
        ),
    ]
