# Generated by Django 5.0.6 on 2024-07-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_pedido_plato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cant_item',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='plato',
        ),
    ]
