# Generated by Django 5.0.6 on 2024-06-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_plato_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.AutoField(db_column='idPlato', primary_key=True, serialize=False),
        ),
    ]
