# Generated by Django 5.0.6 on 2024-07-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_pedido_comentario_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='descuento_activo',
            field=models.BooleanField(default=False),
        ),
    ]
