# Generated by Django 5.0.6 on 2024-06-15 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_plato_id_proveedor_alter_plato_id_plato'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
