# Generated by Django 5.0.6 on 2024-06-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_agenda_entregas_pedido_alter_plato_id_proveedor'),
        ('usuarios', '0009_cliente_repartidor_delete_proveedor_delete_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregas',
            name='id_repartidor',
            field=models.ForeignKey(db_column='id_repatidor', on_delete=django.db.models.deletion.CASCADE, to='usuarios.repartidor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_agenda',
            field=models.ForeignKey(blank=True, db_column='id_agenda', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.agenda'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_repartidor',
            field=models.ForeignKey(blank=True, db_column='id_repatidor', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.repartidor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='plato',
            field=models.ForeignKey(db_column='id_plato', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.plato'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pedido'),
        ),
    ]
