# Generated by Django 5.0.6 on 2024-06-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartidor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repartidor',
            old_name='numero_telf',
            new_name='fono_repartidor',
        ),
        migrations.AddField(
            model_name='repartidor',
            name='apellido_repartidor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='email_repartidor',
            field=models.EmailField(default='repartidor@email.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repartidor',
            name='password_repartidor',
            field=models.CharField(default='test1234', max_length=100),
            preserve_default=False,
        ),
    ]
