# Generated by Django 5.0.6 on 2024-06-26 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repartidor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repartidor',
            old_name='rut',
            new_name='rut_repartidor',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='apellido_repartidor',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='email_repartidor',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='nombre_repartidor',
        ),
        migrations.RemoveField(
            model_name='repartidor',
            name='password_repartidor',
        ),
    ]
