# Generated by Django 5.0.6 on 2024-06-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_plato_fecha_publicacion'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_agendada', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('estado_entrega', models.CharField(max_length=100)),
                ('comentario_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_entrega', models.DateField()),
                ('hora_entrega', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('comentario_pedido', models.CharField(max_length=200)),
                ('estado_pedido', models.CharField(max_length=100)),
                ('monto_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cant_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateField()),
                ('retiro_local', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_proveedor',
            field=models.ForeignKey(db_column='idProveedor', on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
    ]
