# Generated by Django 5.0.6 on 2024-06-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_entregas_id_repartidor_pedido_id_agenda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_agenda',
        ),
        migrations.RemoveField(
            model_name='entregas',
            name='id_repartidor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_repartidor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='plato',
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.DeleteModel(
            name='Entregas',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
