# Generated by Django 5.0.6 on 2024-06-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_remove_pedido_id_agenda_and_more'),
        ('usuarios', '0009_cliente_repartidor_delete_proveedor_delete_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_agendada', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('estado_entrega', models.CharField(max_length=100)),
                ('comentario_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_entrega', models.DateField()),
                ('hora_entrega', models.TimeField()),
                ('id_repartidor', models.ForeignKey(db_column='id_repatidor', on_delete=django.db.models.deletion.CASCADE, to='usuarios.repartidor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('comentario_pedido', models.CharField(max_length=200)),
                ('estado_pedido', models.CharField(max_length=100)),
                ('monto_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cant_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateField()),
                ('retiro_local', models.BooleanField(default=True)),
                ('id_agenda', models.ForeignKey(blank=True, db_column='id_agenda', null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.agenda')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('id_repartidor', models.ForeignKey(blank=True, db_column='id_repatidor', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.repartidor')),
                ('plato', models.ForeignKey(db_column='id_plato', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.plato')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pedido'),
        ),
    ]
