# Generated by Django 5.0.6 on 2024-06-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_alter_entregas_id_repartidor_and_more'),
        ('repartidor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entregas',
            new_name='Entrega',
        ),
    ]
