# Generated by Django 5.0.6 on 2024-06-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='plato_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plato',
            name='plato_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='id_plato',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
