# Generated by Django 5.0.6 on 2024-06-26 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('rut_cliente', models.CharField(max_length=12)),
                ('fono_cliente', models.DecimalField(decimal_places=2, max_digits=10, max_length=15)),
                ('empresa', models.CharField(max_length=100)),
                ('direccion_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('saldo_cliente', models.DecimalField(decimal_places=2, default=35000, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
