# Generated by Django 5.0.6 on 2024-06-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_cliente',
            field=models.EmailField(default='example@email.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fono_cliente',
            field=models.DecimalField(decimal_places=2, default=1111, max_digits=10, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='password_cliente',
            field=models.CharField(default=1111, max_length=100),
            preserve_default=False,
        ),
    ]
