# Generated by Django 5.0.6 on 2024-06-24 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_apellido_cliente_cliente_email_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email_cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='password_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='saldo_cliente',
            field=models.DecimalField(decimal_places=2, default=35000, max_digits=10),
        ),
    ]
