# Generated by Django 5.0.6 on 2024-06-14 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0004_rename_desc_plato_plato_descripcion_plato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('monto_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('id_publicacion', models.ForeignKey(db_column='idPlato', default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.plato')),
                ('ventas', models.ForeignKey(db_column='ventas_id_venta', on_delete=django.db.models.deletion.CASCADE, to='usuarios.ventas')),
            ],
        ),
    ]
