# Generated by Django 5.0.6 on 2024-06-15 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_ventas_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='id_publicacion',
        ),
    ]
