# Generated by Django 5.0.6 on 2024-06-15 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_proveedor_id_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='ventas',
        ),
        migrations.AddField(
            model_name='venta',
            name='id_proveedor',
            field=models.ForeignKey(db_column='idProveedor', default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.proveedor'),
        ),
    ]
