# Generated by Django 5.0.6 on 2024-06-15 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_proveedor_ventas_venta_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id_proveedor',
            field=models.ForeignKey(db_column='idProveedor', on_delete=django.db.models.deletion.CASCADE, to='usuarios.proveedor'),
        ),
    ]
