# Generated by Django 5.0.6 on 2024-06-15 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_venta_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, db_column='idProveedor', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.proveedor'),
        ),
    ]
