# Generated by Django 5.0.6 on 2024-06-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_venta_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.AutoField(db_column='idProveedor', primary_key=True, serialize=False),
        ),
    ]
