# Generated by Django 5.0.6 on 2024-06-02 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.IntegerField()),
                ('id_project', models.ForeignKey(db_column='idProject', on_delete=django.db.models.deletion.CASCADE, to='alumnos.project')),
            ],
        ),
    ]
