# Generated by Django 5.0.6 on 2024-06-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('des_categoria', models.CharField(max_length=100)),
                ('nom_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom_plato', models.CharField(max_length=100)),
                ('desc_plato', models.CharField(max_length=200)),
                ('precio_plato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oferta_plato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
