# Generated by Django 5.0.6 on 2024-06-07 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_rename_plato_activo_categoria_cat_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='id_categoria',
            field=models.ForeignKey(db_column='idCategoria', default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogos.categoria'),
        ),
    ]
