# Generated by Django 5.0.6 on 2024-06-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_categoria_foto_categoria_plato_foto_plato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto_categoria',
            field=models.ImageField(blank=True, null=True, upload_to='media/fotos/categorias/'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='foto_plato',
            field=models.ImageField(blank=True, null=True, upload_to='media/fotos/platos/'),
        ),
    ]
