# Generated by Django 5.0.6 on 2024-06-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(db_column='idProveedor', primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
            ],
        ),
    ]
